# swank-codegen - Generate Lisp wrapper code for Swank-enabled programs
#
# This module generates Lisp code that wraps user programs with Swank
# REPL server support. It supports two modes:
#
# - foreground: Swank in main thread, user code in background (daemons)
# - background: User code in main thread, Swank in background (GUI apps)
#
# And multiple registration backends for discovery:
# - xdg: Register in $XDG_RUNTIME_DIR/repl/{protocol}/{name}.json
# - serviceSpec: No runtime registration (discovery via NixOS config)
# - none: No registration
#
# Usage:
#   code = swankCodegen.mkWrapper {
#     name = "my-app";
#     main = "my-app:main";
#     config = replServer.mkConfig {
#       protocol = replServer.protocols.swank;
#       mode = "foreground";
#     };
#   };

{ lib, ... }:

rec {
  # ============================================================================
  # Code Fragments
  # ============================================================================
  #
  # Reusable Lisp code fragments that can be composed into complete wrappers.

  fragments = {
    # Package definition for the wrapper
    packageDef = { name }: ''
      ;;; REPL wrapper for ${name}
      ;;; Generated by buildLisp swank-codegen

      (defpackage :buildlisp-repl-wrapper
        (:use :cl)
        (:export :run))

      (in-package :buildlisp-repl-wrapper)
    '';

    # Portable environment variable access
    getEnvVar = ''
      (defun get-env-var (name)
        "Get environment variable value, portable across implementations."
        #+sbcl (sb-ext:posix-getenv name)
        #+ecl (ext:getenv name)
        #+ccl (ccl:getenv name)
        #-(or sbcl ecl ccl) nil)
    '';

    replIoIsolation = ''
      (defun make-repl-io-bindings ()
        "Return stream bindings that keep Swank away from process stdio."
        (let* ((input (make-string-input-stream ""))
               (output (make-broadcast-stream))
               (io (make-two-way-stream input output)))
          `((*standard-input* . ,input)
            (*standard-output* . ,output)
            (*error-output* . ,output)
            (*trace-output* . ,output)
            (*terminal-io* . ,io)
            (*query-io* . ,io)
            (*debug-io* . ,io))))

      (defun set-swank-symbol-value (package-name symbol-name value)
        (let ((package (find-package package-name)))
          (when package
            (multiple-value-bind (symbol status)
                (find-symbol symbol-name package)
              (when status
                (setf (symbol-value symbol) value)
                t)))))

      (defun install-swank-log-isolation (output)
        (set-swank-symbol-value "SWANK/BACKEND" "*LOG-OUTPUT*" output)
        (set-swank-symbol-value "SWANK" "*LOG-OUTPUT*" output)
        (set-swank-symbol-value "SWANK" "*SWANK-DEBUG-P*" nil))

      (defun install-repl-worker-io-isolation ()
        (multiple-value-bind (bindings-symbol status)
            (find-symbol "*DEFAULT-WORKER-THREAD-BINDINGS*" "SWANK")
          (when status
            (let* ((bindings (make-repl-io-bindings))
                   (vars (mapcar #'car bindings))
                   (old-bindings (symbol-value bindings-symbol)))
              (setf (symbol-value bindings-symbol)
                    (append bindings
                            (remove-if
                             (lambda (binding) (member (car binding) vars))
                             old-bindings)))))))

      (defmacro with-repl-io-isolation (() &body body)
        `(let* ((input (make-string-input-stream ""))
                (output (make-broadcast-stream))
                (io (make-two-way-stream input output))
                (*standard-input* input)
                (*standard-output* output)
                (*error-output* output)
                (*trace-output* output)
                (*terminal-io* io)
                (*query-io* io)
                (*debug-io* io))
           (install-swank-log-isolation output)
           ,@body))
    '';

    # Short-lived client-mode predicate
    #
    # Emitted when the program declares `swank.shortLivedFlags`. The wrapper's
    # `run` uses this predicate to skip the daemon machinery (debugger hook,
    # background Swank server, sandbox stage-2, XDG registration) when the
    # invocation is a one-shot CLI subcommand sharing the same binary.
    #
    # The flag list is closed over at Nix-build time; argv is consulted at
    # invocation time so each subprocess decides independently.
    clientModeP = { shortLivedFlags }: ''
      (defparameter *short-lived-flags*
        '(${lib.concatMapStringsSep " "
              (f: "\"${lib.escape ["\"" "\\"] f}\"")
              shortLivedFlags})
        "Argv flags that mark a short-lived client invocation. Sourced from
      buildLisp's swank.shortLivedFlags option.")

      (defun client-mode-p ()
        "T when sb-ext:*posix-argv* contains any *short-lived-flags* entry.
      Used by the wrapper's run to skip daemon machinery for one-shot CLI
      subcommands."
        (let ((argv #+sbcl sb-ext:*posix-argv* #-sbcl nil))
          (and *short-lived-flags*
               (loop for a in argv
                     thereis (and (stringp a)
                                  (member a *short-lived-flags*
                                          :test #'string=))))))
    '';

    # Swank server startup code
    # Note: logs to *error-output* (not stdout) to avoid corrupting
    # stdio-based protocols like MCP JSON-RPC.
    swankStartup = { config }: ''
      (defun start-repl-server ()
        "Start Swank server and return the actual port, or NIL on failure.
         Tries configured port first; on address-in-use, retries with port 0
         (OS-assigned). Any error is caught — the process continues without Swank."
        (let* ((configured-port-string (get-env-var "${config.portEnvVar}"))
               (configured-port-from-env
                 (and configured-port-string
                      (ignore-errors
                        (parse-integer configured-port-string :junk-allowed t))))
               (configured-port (or configured-port-from-env ${toString config.port}))
               (create-server (find-symbol "CREATE-SERVER" "SWANK")))
          (unless create-server
            (format *error-output* "~&;; Swank CREATE-SERVER not found, REPL disabled~%")
            (force-output *error-output*)
            (return-from start-repl-server nil))
          (flet ((try-start (port)
                   (funcall create-server
                            :port port
                            :interface "${config.interface}"
                            :dont-close t
                            :style ${config.style})))
            (handler-case
                (let ((actual-port (try-start configured-port)))
                  (format *error-output*
                          "~&Swank server started on ${config.interface}:~a (style ${config.style})~%"
                          actual-port)
                  (force-output *error-output*)
                  actual-port)
              ;; Default port collisions use an ephemeral fallback for parallel sessions.
              ;; An env-selected port is a caller contract; failing closed prevents
              ;; clients from attaching to a stale process on the requested port.
              (#+sbcl sb-bsd-sockets:address-in-use-error #-sbcl error (e)
                (cond
                  (configured-port-from-env
                   (format *error-output*
                           "~&;; Swank port ~a from ${config.portEnvVar} is in use (~a); refusing ephemeral fallback.~%"
                           configured-port e)
                   (force-output *error-output*)
                   #+sbcl (sb-ext:exit :code 1 :abort t)
                   #-sbcl (error "Swank port ~a from ${config.portEnvVar} is in use"
                                 configured-port))
                  (t
                   (format *error-output*
                           "~&;; Swank port ~a in use (~a), trying ephemeral port...~%"
                           configured-port e)
                   (force-output *error-output*)
                   (handler-case
                       (let ((actual-port (try-start 0)))
                         (format *error-output*
                                 "~&Swank server started on ${config.interface}:~a (ephemeral, style ${config.style})~%"
                                 actual-port)
                         (force-output *error-output*)
                         actual-port)
                     (error (e2)
                       (format *error-output*
                               "~&;; Swank ephemeral port also failed: ~a~%;; Continuing without REPL.~%"
                               e2)
                       (force-output *error-output*)
                       nil)))))
              ;; Any other error — log and continue without Swank
              (error (e)
                (format *error-output*
                        "~&;; Swank startup failed: ~a~%;; Continuing without REPL.~%"
                        e)
                (force-output *error-output*)
                nil)))))
    '';

    # Main function invocation via find-symbol (no read-time dependency)
    # Uses :from-end t to handle both pkg:sym and pkg::sym (exported vs internal)
    mainInvocation = { main }: ''
      (defun invoke-main ()
        "Invoke the user's main function."
        (let* ((main-spec "${main}")
               (colon-pos (position #\: main-spec :from-end t))
               (pkg-name (string-upcase (subseq main-spec 0 (position #\: main-spec))))
               (fn-name (string-upcase (subseq main-spec (1+ colon-pos))))
               (main-fn (find-symbol fn-name pkg-name)))
          (if main-fn
              (funcall main-fn)
              (error "Could not find main function: ~a" main-spec))))
    '';

    # Sandbox stage-2 initialization (Landlock + seccomp self-filter)
    # Applied after REPL starts but before user main, making sandbox irreversible.
    # No-op when not running under bwrap sandbox launcher (SANDBOX_BPF_SELF not set).
    sandboxStage2 = { name }: ''
      (defun apply-sandbox-stage2 ()
        "Apply Lisp-side sandbox (stage 2) if running under bwrap launcher.
         Adds Landlock filesystem restrictions + seccomp self-filter.
         Non-fatal: logs warning and continues with bwrap stage-1 only on failure."
        (let ((make-profile (find-symbol "MAKE-PROFILE-FROM-ENV" "SANDBOX"))
              (apply-sandbox (find-symbol "APPLY-SANDBOX" "SANDBOX")))
          (when (and make-profile apply-sandbox)
            (let ((profile (funcall make-profile)))
              (when profile
                (handler-case
                    (funcall apply-sandbox profile :log-stream *error-output*)
                  (error (e)
                    (format *error-output* "~&[${name}] WARNING: sandbox stage-2 failed: ~A~%" e)
                    (format *error-output* "~&[${name}] Continuing with bwrap stage-1 only~%")
                    (force-output *error-output*))))))))
    '';

    # Event loop for :fd-handler style
    eventLoop = {
      fdHandler = ''
        ;; Event loop for :fd-handler style - process fd-handlers for Swank
        ;; The 0.01s timeout ensures responsive handling.
        (loop
          (handler-case
              (sb-sys:serve-event 0.01)
            ;; Broken-pipe and stream errors: invalidate the fd to stop the loop
            (stream-error (c)
              (format *error-output* "~&;; REPL stream error: ~a~%" c)
              (force-output *error-output*)
              (ignore-errors
                (let ((stream (stream-error-stream c)))
                  (when (typep stream 'sb-sys:fd-stream)
                    (let ((fd (sb-sys:fd-stream-fd stream)))
                      (when fd
                        (sb-sys:invalidate-descriptor fd)))))))
            ;; Other errors: just log and continue
            (serious-condition (c)
              (format *error-output* "~&;; REPL event loop error: ~a~%" c)
              (force-output *error-output*))))
      '';

      # Keep-alive loop for :spawn style
      spawn = ''
        ;; Keep-alive loop for :spawn style
        ;; Swank manages its own threads, main thread just stays alive
        (loop (sleep 3600))
      '';
    };

    # Thread-aware debugger hook for background mode
    # Prevents debugger cascade when terminal disconnects:
    # - Main thread errors: fatal exit with backtrace (process should restart)
    # - Worker thread errors: log + abort thread cleanly (process continues)
    #
    # Uses sb-ext:*invoke-debugger-hook* (SBCL-specific) because it catches ALL
    # debugger entries including break, unlike ANSI *debugger-hook*.
    #
    # Pattern from swank-mcp/server/main.lisp:16-52, proven in production.
    threadAwareDebuggerHook = { name }: ''
      (defvar *background-main-thread* nil
        "The thread running the main function. Set at startup.
         Errors on this thread are fatal; errors on other threads
         (Swank handlers, user-spawned) are logged and aborted.")

      (defun install-thread-aware-debugger-hook ()
        "Install debugger hook that only crashes process for main-thread errors.
         SBCL calls sb-ext:*invoke-debugger-hook* BEFORE *debugger-hook*, so we
         must target the SBCL-specific hook for complete coverage."
        (setf *background-main-thread* sb-thread:*current-thread*)
        ;; Prevent Swank from overriding our hook on new connections
        ;; (Swank's install-debugger checks this variable)
        (let ((global-debugger (find-symbol "*GLOBAL-DEBUGGER*" "SWANK")))
          (when global-debugger
            (setf (symbol-value global-debugger) nil)))
        ;; Store our hook in a named function for easier debugging
        (flet ((thread-aware-hook (condition previous-hook)
                 (declare (ignore previous-hook))
                 (let ((current sb-thread:*current-thread*))
                   (cond
                     ;; Main thread error → fatal (process should be restarted by supervisor)
                     ((or (null *background-main-thread*)
                          (eq current *background-main-thread*))
                      (format *error-output* "~&[${name}] FATAL on main thread: ~A~%" condition)
                      (sb-debug:print-backtrace :stream *error-output* :count 20)
                      (force-output *error-output*)
                      (sb-ext:exit :code 1))
                     ;; Other thread → log + abort cleanly (process continues)
                     (t
                      (format *error-output*
                              "~&[${name}] WARNING on thread ~S: ~A~%"
                              (sb-thread:thread-name current) condition)
                      (force-output *error-output*)
                      (let ((abort (find-restart 'abort condition)))
                        (when abort (invoke-restart abort)))
                      ;; No abort restart: return from hook and let thread die naturally.
                      ;; Do NOT exit - killing the process for worker thread errors is wrong.
                      ;; The thread will either handle the error itself or terminate.
                      nil)))))
          ;; SBCL-specific hook (called first, before CL *debugger-hook*)
          (setf sb-ext:*invoke-debugger-hook* #'thread-aware-hook))
        ;; CL standard hook as fallback (also thread-aware)
        (setf *debugger-hook*
              (lambda (condition old-hook)
                (declare (ignore old-hook))
                (let ((current sb-thread:*current-thread*))
                  (cond
                    ;; Main thread: fatal
                    ((or (null *background-main-thread*)
                         (eq current *background-main-thread*))
                     (format *error-output* "~&[${name}] Unhandled error: ~A~%" condition)
                     (sb-debug:print-backtrace :stream *error-output* :count 20)
                     (force-output *error-output*)
                     (sb-ext:exit :code 1))
                    ;; Worker thread: log and let die
                    (t
                     (format *error-output* "~&[${name}] Worker thread error (non-fatal): ~A~%"
                             condition)
                     (force-output *error-output*)
                     nil)))))
        ;; Defense-in-depth: redirect *debug-io* away from terminal
        ;; If built-in debugger activates despite hooks, it writes to stderr
        ;; and gets immediate EOF instead of hanging on terminal read
        (setf *debug-io* (make-two-way-stream
                           (make-string-input-stream "")
                           *error-output*))
        ;; Log that hook was installed (helps debug if it's being overwritten)
        (format *error-output* "~&[${name}] Debugger hook installed~%")
        (force-output *error-output*))
    '';
  };

  # ============================================================================
  # Registration Backends
  # ============================================================================
  #
  # Code generators for different discovery registration methods.

  registration = {
    # XDG runtime directory registration (session-scoped)
    # Creates: $XDG_RUNTIME_DIR/repl/{protocol}/{session-id}/{name}.json
    # Session ID from REPL_SESSION_ID env var (falls back to PID)
    xdg = { name, protocol, kind ? "daemon" }: ''
      (defun ensure-directory-namestring (dir)
        "Ensure DIR string ends with / so merge-pathnames treats it as a directory."
        (if (and (> (length dir) 0)
                 (char/= (char dir (1- (length dir))) #\/))
            (concatenate 'string dir "/")
            dir))

      (defun repl-session-id ()
        "Get REPL session ID from environment, falling back to PID."
        (or (get-env-var "REPL_SESSION_ID")
            (format nil "pid-~a" #+sbcl (sb-posix:getpid) #-sbcl 0)))

      (defun repl-runtime-dir ()
        "Get XDG runtime dir as a directory namestring (trailing slash)."
        (ensure-directory-namestring
          (or (get-env-var "XDG_RUNTIME_DIR")
              (format nil "/run/user/~a"
                      #+sbcl (sb-posix:getuid)
                      #-sbcl 1000))))

      (defun repl-session-dir ()
        "Get session-scoped registration directory."
        (merge-pathnames
          (format nil "repl/${protocol.name}/~a/" (repl-session-id))
          (repl-runtime-dir)))

      (defun clean-stale-sessions ()
        "Remove registration dirs where all PIDs are dead."
        (ignore-errors
          (let* ((base-dir (merge-pathnames "repl/${protocol.name}/"
                                            (repl-runtime-dir)))
                 (session-dirs (ignore-errors (directory
                   (merge-pathnames "*/" base-dir)))))
            (dolist (sdir session-dirs)
              (let ((all-dead t))
                ;; Check each .json file in the session dir
                (dolist (f (ignore-errors (directory
                             (merge-pathnames "*.json" sdir))))
                  (handler-case
                      (let* ((content (ignore-errors (uiop:read-file-string f)))
                             ;; Extract pid from JSON without requiring yason
                             (pid-start (when content (search "\"pid\":" content)))
                             (pid-val (when pid-start
                                        (ignore-errors
                                          (parse-integer content
                                            :start (+ pid-start 6)
                                            :junk-allowed t)))))
                        (when (and pid-val (probe-file (format nil "/proc/~d" pid-val)))
                          (setf all-dead nil)))
                    (error () nil)))
                ;; If all PIDs dead, remove the session dir
                (when all-dead
                  (dolist (f (ignore-errors (directory
                               (merge-pathnames "*.json" sdir))))
                    (ignore-errors (delete-file f)))
                  (ignore-errors (uiop:delete-empty-directory sdir))))))))

      (defun register-repl (port)
        "Register REPL server in session-scoped XDG directory for discovery."
        (let* ((session-dir (repl-session-dir))
               (file (merge-pathnames "${name}.json" session-dir))
               (pid #+sbcl (sb-posix:getpid) #-sbcl 0))
          (ensure-directories-exist session-dir)
          (with-open-file (out file :direction :output :if-exists :supersede)
            (format out "{\"name\":\"${name}\",\"protocol\":\"${protocol.name}\",\"port\":~a,\"pid\":~a,\"kind\":\"${kind}\",\"session\":\"~a\",\"started\":~a}"
                    port pid (repl-session-id) (get-universal-time)))
          (clean-stale-sessions)))

      (defun unregister-repl ()
        "Remove REPL registration file. Removes session dir if empty."
        (ignore-errors
          (let* ((session-dir (repl-session-dir))
                 (file (merge-pathnames "${name}.json" session-dir)))
            (delete-file file)
            ;; Clean up session dir if empty
            (unless (directory (merge-pathnames "*.json" session-dir))
              (ignore-errors (uiop:delete-empty-directory session-dir))))))
    '';

    # Global registration (shared services, cross-session)
    # Creates: $XDG_RUNTIME_DIR/repl/{protocol}/shared/{name}.json
    # For shared services (task-dashboard, task-mcp HTTP) that outlive sessions
    global = { name, protocol, kind ? "daemon" }: ''
      (defun ensure-directory-namestring (dir)
        "Ensure DIR string ends with / so merge-pathnames treats it as a directory."
        (if (and (> (length dir) 0)
                 (char/= (char dir (1- (length dir))) #\/))
            (concatenate 'string dir "/")
            dir))

      (defun repl-runtime-dir ()
        "Get XDG runtime dir as a directory namestring (trailing slash)."
        (ensure-directory-namestring
          (or (get-env-var "XDG_RUNTIME_DIR")
              (format nil "/run/user/~a"
                      #+sbcl (sb-posix:getuid)
                      #-sbcl 1000))))

      (defun repl-shared-dir ()
        "Get shared registration directory (not session-scoped)."
        (merge-pathnames "repl/${protocol.name}/shared/" (repl-runtime-dir)))

      (defun port-alive-p (port)
        "Check if something is listening on PORT via TCP connect test."
        (ignore-errors
          (let ((socket (make-instance 'sb-bsd-sockets:inet-socket
                                       :type :stream :protocol :tcp)))
            (unwind-protect
                (handler-case
                    (progn
                      (setf (sb-bsd-sockets:sockopt-reuse-address socket) t)
                      (sb-bsd-sockets:socket-connect socket #(127 0 0 1) port)
                      t)
                  (sb-bsd-sockets:connection-refused-error () nil)
                  (error () nil))
              (ignore-errors (sb-bsd-sockets:socket-close socket))))))

      (defun clean-stale-shared ()
        "Remove shared registrations where port is not listening."
        (ignore-errors
          (let* ((shared-dir (repl-shared-dir))
                 (files (ignore-errors (directory
                          (merge-pathnames "*.json" shared-dir)))))
            (dolist (f files)
              (handler-case
                  (let* ((content (ignore-errors (uiop:read-file-string f)))
                         ;; Extract port from JSON
                         (port-start (when content (search "\"port\":" content)))
                         (port-val (when port-start
                                     (ignore-errors
                                       (parse-integer content
                                         :start (+ port-start 7)
                                         :junk-allowed t)))))
                    ;; Remove if port not responding
                    (when (and port-val (not (port-alive-p port-val)))
                      (ignore-errors (delete-file f))))
                (error () nil))))))

      (defun register-repl (port)
        "Register REPL server in shared XDG directory for cross-session discovery."
        (let* ((shared-dir (repl-shared-dir))
               (file (merge-pathnames "${name}.json" shared-dir))
               (pid #+sbcl (sb-posix:getpid) #-sbcl 0))
          (ensure-directories-exist shared-dir)
          (with-open-file (out file :direction :output :if-exists :supersede)
            (format out "{\"name\":\"${name}\",\"protocol\":\"${protocol.name}\",\"port\":~a,\"pid\":~a,\"kind\":\"${kind}\",\"shared\":true,\"started\":~a}"
                    port pid (get-universal-time)))
          (clean-stale-shared)))

      (defun unregister-repl ()
        "Remove REPL registration file from shared directory."
        (ignore-errors
          (let* ((shared-dir (repl-shared-dir))
                 (file (merge-pathnames "${name}.json" shared-dir)))
            (delete-file file))))
    '';

    # serviceSpec registration (NixOS config introspection)
    # No runtime registration needed - discovery via NixOS config
    serviceSpec = { name, protocol, kind ? "daemon" }: ''
      (defun register-repl (port)
        "No-op: ${name} uses serviceSpec discovery (NixOS config for ${protocol.name})."
        (declare (ignore port)))

      (defun unregister-repl ()
        "No-op: ${name} uses serviceSpec discovery.")
    '';

    # No registration
    none = { name, protocol, kind ? "daemon" }: ''
      (defun register-repl (port)
        "No-op: ${name} (${protocol.name}) has registration disabled."
        (declare (ignore port)))

      (defun unregister-repl ()
        "No-op: ${name} has registration disabled.")
    '';
  };

  # ============================================================================
  # Complete Wrappers
  # ============================================================================

  # Foreground mode: REPL in main thread, user code in background
  # This is the daemon pattern - Swank event loop runs forever
  #
  # Includes thread-aware debugger hook (same as backgroundWrapper) so that
  # worker thread errors (e.g. Swank connection handlers in :spawn mode)
  # are logged and aborted instead of entering the interactive debugger.
  foregroundWrapper = { name, main, config, sandboxEnabled ? false }: ''
    ${fragments.packageDef { inherit name; }}

    ${fragments.getEnvVar}

    ${fragments.clientModeP { shortLivedFlags = config.shortLivedFlags or []; }}

    ${fragments.replIoIsolation}

    ${fragments.swankStartup { inherit config; }}

    ${fragments.mainInvocation { inherit main; }}

    ${registration.${config.registration} {
      inherit name;
      protocol = config.protocol;
      kind = config.extra.kind or "daemon";
    }}

    ${lib.optionalString sandboxEnabled (fragments.sandboxStage2 { inherit name; })}

    ${fragments.threadAwareDebuggerHook { inherit name; }}

    (defun run ()
      "REPL in main thread, user code in background thread.
    When CLIENT-MODE-P is true, bypass the daemon machinery and invoke main
    directly — short-lived CLI subcommands do not need Swank, registration,
    or sandbox stage-2."
      (cond
        ((client-mode-p)
         (invoke-main))
        (t
         ;; Install thread-aware debugger hook FIRST, before any threads start.
         ;; This prevents worker thread errors from entering the interactive debugger.
         (install-thread-aware-debugger-hook)
         (install-repl-worker-io-isolation)
         (let ((port (with-repl-io-isolation ()
                       (start-repl-server))))
           (when port (register-repl port))
           ${lib.optionalString sandboxEnabled ";; Apply sandbox stage-2 (Landlock + seccomp) before user code\n           (apply-sandbox-stage2)"}
           ;; Run main in background thread so it can block freely
           (sb-thread:make-thread
             (lambda ()
               (handler-case
                   (invoke-main)
                 (serious-condition (c)
                   (format *error-output* "~&;; Main function error: ~a~%" c)
                   (force-output *error-output*))))
             :name "user-main")
           ;; Main thread runs event loop or sleep
           (with-repl-io-isolation ()
             ${if config.style == ":spawn" then fragments.eventLoop.spawn
               else fragments.eventLoop.fdHandler})))))
  '';

  # Background mode: User code in main thread, REPL in background
  # This is for GUI apps, scripts, and MCP servers - main thread owns execution
  #
  # Includes thread-aware debugger hook to prevent cascade when terminal disconnects:
  # errors on main thread are fatal (exit 1), errors on worker threads abort cleanly.
  backgroundWrapper = { name, main, config, sandboxEnabled ? false }: ''
    ${fragments.packageDef { inherit name; }}

    ${fragments.getEnvVar}

    ${fragments.clientModeP { shortLivedFlags = config.shortLivedFlags or []; }}

    ${fragments.replIoIsolation}

    ${fragments.swankStartup { inherit config; }}

    ${fragments.mainInvocation { inherit main; }}

    ${registration.${config.registration} {
      inherit name;
      protocol = config.protocol;
      kind = config.extra.kind or "daemon";
    }}

    ${lib.optionalString sandboxEnabled (fragments.sandboxStage2 { inherit name; })}

    ${fragments.threadAwareDebuggerHook { inherit name; }}

    (defun run ()
      "User code in main thread, REPL in background thread.
    When CLIENT-MODE-P is true, bypass the daemon machinery and invoke main
    directly — short-lived CLI subcommands do not need Swank, registration,
    or sandbox stage-2."
      (cond
        ((client-mode-p)
         (invoke-main))
        (t
         ;; Install thread-aware debugger hook FIRST, before any threads start.
         ;; This prevents debugger cascade when terminal disconnects.
         (install-thread-aware-debugger-hook)
         (install-repl-worker-io-isolation)
         ;; Start REPL in background thread - registration happens in same thread
         ;; to avoid race condition (main thread might check port before it's set)
         (sb-thread:make-thread
           (lambda ()
             (with-repl-io-isolation ()
               (let ((port (start-repl-server)))
                 (when port (register-repl port))
                 ${if config.style == ":fd-handler" then ''
                 ;; :fd-handler needs its own event loop in the background thread
                 (loop
                   (handler-case
                       (sb-sys:serve-event 0.1)
                     (serious-condition (c)
                       (format *error-output* "~&;; REPL error: ~a~%" c))))
                 '' else ''
                 ;; :spawn manages its own threads, nothing more to do
                 ''})))
           :name "repl-server")
         ;; Give REPL time to start and register
         (sleep 0.2)
         ${lib.optionalString sandboxEnabled ";; Apply sandbox stage-2 (Landlock + seccomp) before user code\n         (apply-sandbox-stage2)"}
         ;; Run main in main thread (unwind-protect for cleanup)
         (unwind-protect
             (invoke-main)
           (unregister-repl)))))
  '';

  # ============================================================================
  # Public API
  # ============================================================================

  # Generate wrapper code based on configuration
  #
  # Parameters:
  #   name: Application name (used for registration)
  #   main: Main function specifier (e.g., "my-app:main")
  #   config: Configuration from replServer.mkConfig
  #   sandboxEnabled: Whether to inject sandbox stage-2 initialization (default: false)
  #
  # Returns: Lisp source code string
  mkWrapper = { name, main, config, sandboxEnabled ? false }:
    if config.mode == "foreground"
    then foregroundWrapper { inherit name main config sandboxEnabled; }
    else backgroundWrapper { inherit name main config sandboxEnabled; };
}
